#!/bin/sh
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile"; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.Xresources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -nocpp -merge "$file"
    fi
done

# Load keymaps
for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts.
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Make sure dbus is available then set gsettings
export DISPLAY=:0

set_gsettings() {

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	# No DBUS session running, start one.
	eval `dbus-launch --sh-syntax`
fi

# ALPM hooks still aren't handling this 100% of the time.
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

# Change keyboard layaout
_current_val="$(gsettings get org.gnome.desktop.input-sources sources)"
echo "${_current_val}" > /tmp/.input-sources
if [[ *'[]'* = "${_current_val}" ]]; then
	gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"
fi

# Enabled extensions
_extensions="['user-theme@gnome-shell-extensions.gcampax.github.com', 'status-menu-buttons@dev.antergos.com', 'dash-to-dock@micxgx.gmail.com', 'panel-osd@berend.de.schouwer.gmail.com', 'topIcons@adel.gadllah@gmail.com']"
gsettings set org.gnome.shell enabled-extensions "${_extensions}"

# Extension - Panel-OSD Settings
gsettings set org.gnome.shell.extensions.panel-osd x-pos 96.0
gsettings set org.gnome.shell.extensions.panel-osd y-pos 96.0
gsettings set org.gnome.shell.extensions.panel-osd force-expand true

# Extension - dash-to-dock Settings
gsettings set org.gnome.shell.extensions.dash-to-dock apply-custom-theme false
gsettings set org.gnome.shell.extensions.dash-to-dock opaque-background true
gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.5
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots false
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink false

# Randomly choose a default wallpaper from antergos-wallpapers
DIR="/usr/share/antergos/wallpapers"
PIC=$(ls ${DIR}/* | shuf -n1)

gsettings set org.gnome.desktop.background picture-uri file://${PIC}

# Set favorite apps
gsettings set org.gnome.shell favorite-apps "['Cnchi.desktop', 'nautilus.desktop', 'chromium.desktop', 'pidgin.desktop', 'gnome-music.desktop']"

# Disable screensaver
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
gsettings set org.gnome.desktop.session idle-delay 0

# Set theme
gsettings set org.gnome.desktop.interface gtk-theme 'Numix-Frost-Light'
gsettings set org.gnome.desktop.wm.preferences theme 'Numix-Frost-Light'
gsettings set org.gnome.shell.extensions.user-theme name 'Numix-Frost'

# Set icon theme
gsettings set org.gnome.desktop.interface icon-theme 'Numix-Square'

# Not show desktop icons
gsettings set org.gnome.desktop.background show-desktop-icons false

# Directories befor files in nautilus
gsettings set org.gnome.nautilus.preferences sort-directories-first true

# Minimize and close buttons
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

# Don't Disable terminal bell (accessibility concerns)
gsettings set org.gnome.desktop.wm.preferences audible-bell true

# Configure touchpad
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true

# Set fonts
gsettings set org.gnome.desktop.interface font-name 'Open Sans 12'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Open Sans 13'
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'

# Turn on automatic date/time
gsettings set org.gnome.desktop.datetime automatic-timezone true;
timedatectl set-ntp true

# Terminal Profile
_schema='/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/'
gsettings set /org/gnome/terminal/legacy/profiles:/ default 'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'
gsettings set /org/gnome/terminal/legacy/profiles:/ list "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
gsettings set "${_schema}" use-theme-colors false
gsettings set "${_schema}" background-color '#262626262626'
gsettings set "${_schema}" foreground-color '#F8F8F8F8F2F2'
gsettings set "${_schema}" visible-name 'antergos'
gsettings set "${_schema}" palette "['#1B1B1D1D1E1E', '#F9F926267272', '#8282B4B41414', '#FDFD97971F1F', '#5656C2C2D6D6', '#8C8C5454FEFE', '#464654545757', '#CCCCCCCCC6C6', '#505053535454', '#FFFF59599595', '#B6B6E3E35454', '#FEFEEDED6C6C', '#8C8CEDEDFFFF', '#9E9E6F6FFEFE', '#89899C9CA1A1', '#F8F8F8F8F2F2']"

}

echo "Running set-gsettings..."
set_gsettings > /tmp/.set_gsettings 2>&1;
echo "set-gsettings complete"
gnome-keyring-daemon -rd
echo "X session wrapper complete, running session $@"

exec $@
