#!/bin/sh
#
# LightDM wrapper to run around X sessions.

echo "Running X session wrapper"

# Load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile"; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.Xresources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -nocpp -merge "$file"
    fi
done

# Load keymaps
for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
    if [ -f "$file" ]; then
        echo "Loading keymap: $file"
        setxkbmap `cat "$file"`
        XKB_IN_USE=yes
    fi
done

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
    for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
        if [ -f "$file" ]; then
           echo "Loading modmap: $file"
           xmodmap "$file"
        fi
    done
fi

unset XKB_IN_USE

# Run all system xinitrc shell scripts.
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

# Make sure dbus is available then set gsettings
export DISPLAY=:0

set_gsettings() {

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	# No DBUS session running, start one.
	eval `dbus-launch --sh-syntax`
fi
# Change keyboard layaout
gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"

# Randomly choose a default wallpaper from antergos-wallpapers
DIR="/usr/share/antergos/wallpapers"
PIC=$(ls ${DIR}/* | shuf -n1)

gsettings set org.gnome.desktop.background picture-uri file://${PIC}

# Set favorite apps
gsettings set org.gnome.shell favorite-apps "['Cnchi.desktop', 'nautilus.desktop', 'chromium.desktop', 'pidgin.desktop', 'gnome-music.desktop']"

# Disable screensaver
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
gsettings set org.gnome.desktop.session idle-delay 0

# Enabled extensions
gsettings set org.gnome.shell enabled-extensions \
	"['user-theme@gnome-shell-extensions.gcampax.github.com', 'lockscreen@dev.antergos.com', 'dash-to-dock@micxgx.gmail.com', 'panel-osd@berend.de.schouwer.gmail.com']"

# Extension - Panel-OSD Settings
 gsettings set org.gnome.shell.extensions.panel-osd x-pos 96.0
 gsettings set org.gnome.shell.extensions.panel-osd y-pos 96.0
 gsettings set org.gnome.shell.extensions.panel-osd force-expand true


# Set theme
gsettings set org.gnome.desktop.interface gtk-theme 'Numix Frost Light'
gsettings set org.gnome.desktop.wm.preferences theme 'Numix Frost Light'
gsettings set org.gnome.shell.extensions.user-theme name "Numix Frost Light"

# Set icon theme
gsettings set org.gnome.desktop.interface icon-theme 'Numix-Square'

# Not show desktop icons
gsettings set org.gnome.desktop.background show-desktop-icons false

# Minimize and close buttons
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:maximize,close'

# Disable terminal bell
gsettings set org.gnome.desktop.wm.preferences audible-bell false

# Configure touchpad
gsettings set org.gnome.settings-daemon.peripherals.touchpad tap-to-click true
gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled true
gsettings set org.gnome.settings-daemon.peripherals.touchpad scroll-method 'two-finger-scrolling'

# Set fonts
gsettings set org.gnome.desktop.interface font-name 'Lato 11'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Lato Bold 12'
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'

# Turn on automatic date/time
gsettings set org.gnome.desktop.datetime automatic-timezone true;

}

echo "Running set-gsettings..."
set_gsettings
echo "set-gsettings complete"
gnome-keyring-daemon -rd
echo "X session wrapper complete, running session $@"

exec $@
