#!/bin/sh
# From Manjaroiso to Antergos-iso

source /etc/antergos/functions

LOCALE=$(get_country)
KEYMAP=$(get_keyboard)
KBLAYOUT=$(get_layout)

_set_locales
#locale-gen > /dev/null

# Install chinese fonts
if [ "$LOCALE" = 'zh_TW' ] || [ "$LOCALE" = 'zh_CN' ];then
	pacman --noconfirm -U /arch/pkg/opendesktop-fonts-1.4.2-1-any.pkg.tar.xz
fi

# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)

sudo -u antergos echo ${LOCALE} > /home/antergos/.config/user-dirs.locale

sudo -u antergos xdg-user-dirs-update

systemd-detect-virt -v -q && { sudo depmod -a; modprobe -a vboxguest vboxsf vboxvideo; }

echo "LiveCD Configuration Complete"
exit 0;
