#!/bin/sh
# From Manjaroiso to Antergos-iso

source /etc/antergos/functions

LOCALE=$(get_country)
KEYMAP=$(get_keyboard)
KBLAYOUT=$(get_layout)

_set_locales
#locale-gen > /dev/null

# Install chinese fonts
if [ "$LOCALE" = 'zh_TW' ] || [ "$LOCALE" = 'zh_CN' ];then
	pacman --noconfirm -U /arch/pkg/opendesktop-fonts-1.4.2-1-any.pkg.tar.xz
fi


# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)

echo ${LOCALE} > /home/antergos/.config/user-dirs.locale

su -c "xdg-user-dirs-update" antergos

# Randomly choose a default wallpaper from antergos-wallpapers
DIR="/usr/share/antergos/wallpapers"
PIC=$(ls ${DIR}/* | shuf -n1)

su -c "dbus-launch gsettings set org.gnome.desktop.background picture-uri file://${PIC}" antergos
depmod -a
modprobe -a vboxguest vboxsf vboxvideo
