#!/bin/bash
# From Manjaroiso to Antergos-iso

source /etc/antergos/functions

LOCALE=$(get_country)
KEYMAP=$(get_keyboard)
KBLAYOUT=$(get_layout)

_set_locales
#locale-gen > /dev/null

# Install chinese fonts
if [ "$LOCALE" = 'zh_TW' ] || [ "$LOCALE" = 'zh_CN' ];then
	pacman --noconfirm -U /arch/pkg/opendesktop-fonts-1.4.2-1-any.pkg.tar.xz
fi


# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)

echo ${LOCALE} > /home/antergos/.config/user-dirs.locale

su -c "xdg-user-dirs-update" antergos

modprobe -a vboxguest vboxsf vboxvideo

# Record the highest PID of dbus-launch so we can kill the process that will be spawned by gsettings.
pids=$(ps -ef | grep "dbus-launch" | awk '{print $2}')
echo "${pids}" > /tmp/whitelist

# Set gsettings
su -c "/usr/bin/set-gsettings" antergos >/dev/null 2>&1
sleep 2
rm ${work_dir}/root-image/usr/bin/set-gsettings

# Kill all the dbus processes so we can umount
echo "Finalizing live session..."
newpids=$(ps -ef | grep "dbus-launch" | awk '{print $2}')
echo "${newpids}" > /tmp/greylist
grep -F -v -f /tmp/whitelist /tmp/greylist > /tmp/blacklist
pkill -SIGTERM -F /tmp/blacklist

