#!/bin/bash

# Change default wallpaper
dbus-launch gsettings set org.gnome.desktop.background picture-uri file:///usr/share/cinnarch/wallpapers/cinnarch-wallpaper.png

# Set favorite apps
dbus-launch gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'chromium.desktop', 'empathy.desktop', 'xnoise.desktop']"

# Disable screensaver
dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled false
dbus-launch gsettings set org.gnome.desktop.screensaver idle-activation-enabled false