#!/bin/bash
# -*- coding: utf-8 -*-
#
#  set-gnome-settings
#
#  Copyright © 2013-2016 Antergos
#

gset() {
    _path=$1
    _setting=$2
    _value=$3
    _user=$4
    if [ "${_user}" == "" ]; then
        _user="antergos"
    fi
    su -s /bin/sh -c 'eval $(dbus-launch) ; export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID ; GSETTINGS_BACKEND=dconf gsettings set ${_path} ${_setting} ${_value}' ${_user} || true
}

terminal-profile() {
	_term=$1
	_schema="org.${_term}.Terminal.Legacy.Profile:/org/${_term}/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/"

    gset "org.${_term}.Terminal.ProfilesList" default 'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'

	gset "org.${_term}.Terminal.ProfilesList" list "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
	gset "${_schema}" use-theme-colors false
	gset "${_schema}" background-color '#262626262626'
	gset "${_schema}" foreground-color '#F8F8F8F8F2F2'
	gset "${_schema}" visible-name 'antergos'
	gset "${_schema}" palette "['#1B1B1D1D1E1E', '#F9F926267272', '#8282B4B41414', '#FDFD97971F1F', '#5656C2C2D6D6', '#8C8C5454FEFE', '#464654545757', '#CCCCCCCCC6C6', '#505053535454', '#FFFF59599595', '#B6B6E3E35454', '#FEFEEDED6C6C', '#8C8CEDEDFFFF', '#9E9E6F6FFEFE', '#89899C9CA1A1', '#F8F8F8F8F2F2']"
}

# nohup /usr/lib/gnome-settings-daemon/gnome-settings-daemon > /dev/null &

# Change keyboard layout
# The value of this setting is applied with sed from postinstall.sh before running set-settings.
gset org.gnome.desktop.input-sources sources "[('xkb','us')]"

# Set favorite apps
gset org.gnome.shell favorite-apps "['nautilus.desktop', 'gnome-terminal.desktop', \"${_BROWSER}.desktop\", 'pidgin.desktop', 'gnome-music.desktop']"

# Set enabled extensions
gset org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'status-menu-buttons@dev.antergos.com', 'dash-to-dock@micxgx.gmail.com']"

# Change default wallpaper
gset org.gnome.desktop.background picture-uri file:///usr/share/antergos/wallpapers/antergos-wallpaper.png

# Set GTK Theme
gset org.gnome.desktop.interface gtk-theme "Numix-Frost-Light"
gset org.gnome.desktop.wm.preferences theme "Numix-Frost-Light"
gset org.gnome.shell.extensions.user-theme name "Numix-Frost-Light"

# Set icon theme
gset org.gnome.desktop.interface icon-theme "Numix-Square"

# Min/Max Buttons
gset org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

gset org.gnome.desktop.screensaver lock-enabled false
gset org.gnome.desktop.session idle-delay 0

# Configure touchpad
gset org.gnome.desktop.peripherals.touchpad tap-to-click true
gset org.gnome.desktop.peripherals.touchpad natural-scroll true
gset org.gnome.desktop.peripherals.touchpad scroll-method 'two-finger-scrolling'

terminal-profile 'gnome'

# 6dots (gdm)

gset org.gnome.desktop.interface clock-show-date true gdm
gset org.gnome.desktop.interface accessibility true gdm
gset org.gnome.desktop.interface toolkit-accessibility true gdm

gset org.gnome.desktop.a11y.applications screen-reader-enabled true gdm
#gset org.gnome.desktop.a11y.applications screen-keyboard-enabled true gdm
#gset org.gnome.desktop.a11y.applications screen-magnifier-enabled true gdm
