#!/bin/bash

pacman-key --init && pacman-key --populate archlinux antergos

pacman -Syy yaourt --noconfirm

yaourt -S downgrader --noconfirm 

VAR=$(expect -c "
spawn downgrader -q parted
expect \":: Proceed with installation? [Y/n]\"
send \"Y\r\"
")

echo "==============="
echo "$VAR"

exit 0