#!/bin/sh
# From Manjaroiso to Cinnarch-iso

source /etc/cinnarch/functions

LOCALE=$(get_country)
KEYMAP=$(get_keyboard)
KBLAYOUT=$(get_layout)

_set_locales
#locale-gen > /dev/null

# Install chinese fonts
if [ "$LOCALE" = 'zh_TW' ] || [ "$LOCALE" = 'zh_CN' ];then
	pacman --noconfirm -U /arch/pkg/opendesktop-fonts-1.4.2-1-any.pkg.tar.xz
fi


# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)

echo ${LOCALE} > /home/cinnarch/.config/user-dirs.locale

su -c "xdg-user-dirs-update" cinnarch
