#!/bin/bash

# Change keyboard layaout
dbus-launch gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"

# Randomly choose a default wallpaper from antergos-wallpapers
DIR="/usr/share/antergos/wallpapers"

PIC=$(ls ${DIR}/* | shuf -n1)

dbus-launch gsettings set org.gnome.desktop.background picture-uri file://${PIC}

# Set favorite apps
dbus-launch gsettings set org.gnome.shell favorite-apps "['nautilus.desktop', 'chromium.desktop', 'empathy.desktop', 'xnoise.desktop']"
