#!/bin/sh
# From Manjaroiso to Antergos-iso

source /etc/antergos/functions

GRAPHIC_CARD=`hwinfo --gfxcard|grep 'Model:[[:space:]]'`
if [[ `echo ${GRAPHIC_CARD}|grep -i 'intel[[:space:]]'` != "" ]];then
        cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "sna"
EndSection
EOF
fi


LOCALE=$(get_country)
KEYMAP=$(get_keyboard)
KBLAYOUT=$(get_layout)

_set_locales
#locale-gen > /dev/null

# Install chinese fonts
if [ "$LOCALE" = 'zh_TW' ] || [ "$LOCALE" = 'zh_CN' ];then
	pacman --noconfirm -U /arch/pkg/opendesktop-fonts-1.4.2-1-any.pkg.tar.xz
fi


# load keys
loadkeys $(cat /etc/vconsole.conf | grep "KEYMAP=" | cut -d= -f2)
