#!/bin/bash
set -euo pipefail

ISO_NAME="antergos-plasma"
ISO_LABEL="ANTERGOS"

INSTALL_DIR="arch"
WORK_DIR="/work"
OUT_DIR="/out"

VERBOSE="-v"

# Tell which nvidia drivers include into the iso
NOUVEAU_DRIVER="y"
NVIDIA_DRIVER="n"

# Add ZFS modules
ADD_ZFS_MODULES="y"

# Keep xz packages in cache
KEEP_XZ="y"

# Install iso-hotfix-utility from source
ISO_HOTFIX="y"

# Install Cnchi from git
CNCHI_GIT="n"

# Pacman configuration file
PACMAN_CONF="${WORK_DIR}/pacman.conf"
