#!/bin/bash
set -euo pipefail

ISO_NAME="antergos-netcli"
ISO_LABEL="ANTERGOS"

YEAR="$(date +'%y')"
MONTH="$(date +'%-m')"
ISO_VERSION="${YEAR}.${MONTH}"

INSTALL_DIR="arch"
WORK_DIR="/work"
OUT_DIR="/out"

ARCH=$(uname -m)
VERBOSE="-v"
SCRIPT_PATH=$(readlink -f ${0%/*})

# Tell which nvidia drivers include into the iso
NOUVEAU_DRIVER="n"
NVIDIA_DRIVER="n"

# Add ZFS modules
ADD_ZFS_MODULES="n"

# Keep xz packages in cache
KEEP_XZ="n"

# Install iso-hotfix-utility from source
ISO_HOTFIX="n"
ISO_HOTFIX_UTILITY_VERSION="1.0.17"
ISO_HOTFIX_UTILITY_URL="https://github.com/Antergos/iso-hotfix-utility/archive/${ISO_HOTFIX_UTILITY_VERSION}.tar.gz"

# Pacman configuration file
PACMAN_CONF="${WORK_DIR}/pacman.conf"
